# syntax=docker/dockerfile:1
FROM node:12.13.1 AS builder

WORKDIR /usr/src/app

COPY ./app/qiwen-file-web/package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci --production

COPY ./app/qiwen-file-web .

RUN --mount=type=cache,target=/root/.npm \
    npm install && npm run build

# 使用轻量级的 nginx 镜像来服务静态文件
FROM nginx:alpine

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8081

CMD ["nginx", "-g", "daemon off;"]